# Generated by Django 4.2 on 2024-09-16 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mandatoryuser',
            name='url',
            field=models.URLField(),
        ),
    ]
