# Generated by Django 4.2 on 2024-09-16 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_alter_mandatoryuser_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mandatoryuser',
            name='chat_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mandatory', to='bot.user'),
        ),
    ]
