# Generated by Django 4.2 on 2024-09-16 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_alter_mandatoryuser_chat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='mandatoryuser',
            name='channel_id',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
