START_TEXT = 'Botimizdan foydalanish uchun quyidagi kanallarimizga obuna bo‘ling'
SOATBAY_TEXT = '🕓 Soatbay'
HOMEEDUCATION_TEXT = "🏘 Uyda ta'lim"
HIGHCLASS_TEXT = '👨‍🎓 Yuqori sinf'
PRIMARYCLASS_TEXT = "👦 Boshlang'ich sinf"
DECREE_TEXT = "Dekret"
WORKING_TEXT = "🏖 Mehnat ta'tili (otpusknoy)"
BACK_TEXT = "🔙 Boshiga qaytish"
TEXT_ = "Azolikni tekshirish ✔️"
